#!/usr/bin/env bash

# practically everything here is copied from somewhere else

# exit script if any command fails
set -e

# Close any open System Preferences panes, to prevent them from overriding
# settings we’re about to change
osascript -e 'tell application "System Preferences" to quit'

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until setup has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

###############################################################################
# Mac system preferences                                                      #
###############################################################################

# Disable the 'Are you sure you want to open this application?' dialog
defaults write com.apple.LaunchServices LSQuarantine -bool false

# Disable press-and-hold for keys in favor of key repeat
defaults write NSGlobalDomain ApplePressAndHoldEnabled -bool false

# Trackpad: enable tap to click for this user and for the login screen
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -bool true
defaults -currentHost write NSGlobalDomain com.apple.mouse.tapBehavior -int 1
defaults write NSGlobalDomain com.apple.mouse.tapBehavior -int 1

# Set a blazingly fast keyboard repeat rate
defaults write NSGlobalDomain KeyRepeat -int 1
defaults write NSGlobalDomain InitialKeyRepeat -int 10

# Reveal IP, hostname, OS, etc. when clicking clock in login window
sudo defaults write /Library/Preferences/com.apple.loginwindow AdminHostInfo HostName

###############################################################################
# Brew                                                                        #
###############################################################################

ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
echo 'export PATH="/usr/local/bin:$PATH"' >> ~/.bash_profile
brew doctor
brew update
brew upgrade --all

brew install zsh
brew install git
brew install tmux 
brew install reattach-to-user-namespace
brew install mvim
# for the youcompleteme vim plugin
brew install cmake
brew install gnupg2
brew install fzf
brew install z
brew install python
brew install virtualenv

###############################################################################
# pip                                                                         #
###############################################################################

pip install virtualenvwrapper

VENV_WRAPPER=/usr/local/bin/virtualenvwrapper.sh
 
if [ -f "$VENV_WRAPPER" ]
then
    source $VENV_WRAPPER
fi
###############################################################################
# Git setup                                                                   #
###############################################################################

git config --global user.name "Zhiyan Foo"
git config --global user.email "zhiyanfoo@gmail.com"
git config --global credential.helper osxkeychain

###############################################################################
# ruby version manager                                                        #
###############################################################################

\curl -sSL https://get.rvm.io | bash -s -- --ignore-dotfiles

###############################################################################
# dotfiles                                                                    #
###############################################################################
git clone "https://github.com/zhiyanfoo/dotfiles" ~/dotfiles
ln -s ~/dotfiles/.aliases ~/.aliases
rm ~/.bash_profile
ln -s ~/dotfiles/.bash_profile ~/.bash_profile
ln -s ~/dotfiles/.commonprofile ~/.commonprofile
ln -s ~/dotfiles/.functions ~/.functions
ln -s ~/dotfiles/.tmux.conf ~/.tmux.conf
ln -s ~/dotfiles/.vimrc ~/.vimrc
ln -s ~/dotfiles/.zshrc ~/.zshrc

###############################################################################
# vim plugins                                                                 #
###############################################################################

# Needs fixing vimrc
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
/usr/local/bin/mvim -v --cmd +PluginInstall +qall

cd ~/.vim/bundle/YouCompleteMe
./install.py --clang-completer
/usr/local/bin/mvim -v +PluginInstall +qall

###############################################################################
# Snippets                                                                    #
###############################################################################

mkdir -p ~/.utils
mkdir -p ~/.vim/UltiSnips

git clone "https://github.com/zhiyanfoo/vim-snippets" ~/.utils/vim-snippets

ln -s ~/.utils/vim-snippets/UltiSnips/python.snippets ~/.vim/UltiSnips/python.snippets
ln -s ~/.utils/vim-snippets/UltiSnips/java.snippets ~/.vim/UltiSnips/java.snippets
ln -s ~/.utils/vim-snippets/UltiSnips/snippets.snippets ~/.vim/UltiSnips/snippets.snippets 
ln -s ~/.utils/vim-snippets/UltiSnips/tex.snippets ~/.vim/UltiSnips/tex.snippets
ln -s ~/.utils/vim-snippets/UltiSnips/texmath.snippets ~/.vim/UltiSnips/texmath.snippets
ln -s ~/.utils/vim-snippets/UltiSnips/bib.snippets ~/.vim/UltiSnips/bib.snippets 

###############################################################################
# Apps                                                                        #
###############################################################################

# preferences for iterm need to be changed manually, profile -> colors and
# profile -> general -> command -> /usr/local/bin/zsh
brew cask install --appdir="~/Applications" iterm2
brew cask install --appdir="/Applications" firefox
brew cask install --appdir="/Applications" skim
brew cask install --appdir="/Applications" vlc
brew cask install --appdir="/Applications" google-chrome
brew cask install --appdir="/Applications" vagrant
