#!/usr/bin/env bash

# practically everything here is copied from somewhere else

# exit script if any command fails
set -e

# Close any open System Preferences panes, to prevent them from overriding
# settings we’re about to change
osascript -e 'tell application "System Preferences" to quit'

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until setup has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

###############################################################################
# Mac system preferences                                                      #
###############################################################################

# Disable the 'Are you sure you want to open this application?' dialog
defaults write com.apple.LaunchServices LSQuarantine -bool false

# Disable press-and-hold for keys in favor of key repeat
defaults write NSGlobalDomain ApplePressAndHoldEnabled -bool false

# Trackpad: enable tap to click for this user and for the login screen
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -bool true
defaults -currentHost write NSGlobalDomain com.apple.mouse.tapBehavior -int 1
defaults write NSGlobalDomain com.apple.mouse.tapBehavior -int 1

# Disable the sound effects on boot
sudo nvram SystemAudioVolume=" "
# add sound effect back
# sudo nvram -d SystemAudioVolume

# Disable Dashboard
# defaults write com.apple.dashboard mcx-disabled -bool true

# Don’t show Dashboard as a Space
# defaults write com.apple.dock dashboard-in-overlay -bool true

# (Use karabiner instead) Set a blazingly fast keyboard repeat rate 
# defaults write -g InitialKeyRepeat -int 10 # normal minimum is 15 (225 ms)
# defaults write -g KeyRepeat -int 1 # normal minimum is 2 (30 ms)

# Reveal IP, hostname, OS, etc. when clicking clock in login window
sudo defaults write /Library/Preferences/com.apple.loginwindow AdminHostInfo HostName

# Prevent Time Machine from prompting to use new hard drives as backup volume
defaults write com.apple.TimeMachine DoNotOfferNewDisksForBackup -bool true

###############################################################################
# Brew                                                                        #
###############################################################################

ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
echo 'export PATH="/usr/local/bin:$PATH"' >> ~/.bash_profile
brew doctor
brew update
brew upgrade --all

brew install zsh
brew install git
brew install tmux 
brew install reattach-to-user-namespace
brew install python
brew install python3
brew install neovim
# for the youcompleteme vim plugin
brew install cmake
brew install gnupg2
brew install fzf
brew install z
brew install virtualenv
brew install ranger
brew install universal-ctags
brew install rename
brew install youtube-dl
brew install unrar
brew install coreutils
brew install findutils

###############################################################################
# pip                                                                         #
###############################################################################

pip install virtualenvwrapper

VENV_WRAPPER=/usr/local/bin/virtualenvwrapper.sh
 
if [ -f "$VENV_WRAPPER" ]
then
    source $VENV_WRAPPER
fi
###############################################################################
# Git setup                                                                   #
###############################################################################

git config --global user.name "Zhiyan Foo"
git config --global user.email "zhiyanfoo@gmail.com"
git config --global credential.helper osxkeychain

###############################################################################
# ruby version manager                                                        #
###############################################################################

\curl -sSL https://get.rvm.io | bash -s -- --ignore-dotfiles

###############################################################################
# dotfiles                                                                    #
###############################################################################
git clone "https://github.com/zhiyanfoo/dotfiles" ~/dotfiles
ln -s ~/dotfiles/aliases ~/.aliases
rm ~/.bash_profile
ln -s ~/dotfiles/bash_profile ~/.bash_profile
ln -s ~/dotfiles/commonprofile ~/.commonprofile
ln -s ~/dotfiles/functions ~/.functions
ln -s ~/dotfiles/tmux.conf ~/.tmux.conf
ln -s ~/dotfiles/vimrc ~/.vimrc
ln -s ~/dotfiles/zshrc ~/.zshrc
ln -s ~/dotfiles/global_gitignore ~/.global_gitignore
mkdir -p .config/nvim/
ln -s ~/dotfiles/nvim_init.vim ~/.config/nvim/init.vim


###############################################################################
# vim plugins                                                                 #
###############################################################################

# Needs fixing vimrc
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
/usr/local/bin/mvim -v --cmd +PluginInstall +qall

cd ~/.vim/bundle/YouCompleteMe
./install.py --clang-completer
/usr/local/bin/mvim -v +PluginInstall +qall

###############################################################################
# Snippets                                                                    #
###############################################################################

mkdir -p ~/.vim/UltiSnips
mkdir -p ~/tools

git clone "https://github.com/honza/vim-snippets" ~/tools/vim-snippets
git clone "https://github.com/zhiyanfoo/snippets" ~/tools/z-snippets
./~/tools/z-snippets/create_symlinks.sh

###############################################################################
# Apps                                                                        #
###############################################################################

brew cask install --appdir="~/Applications" iterm2
brew cask install --appdir="/Applications" firefox
brew cask install --appdir="/Applications" skim
brew cask install --appdir="/Applications" vlc
brew cask install --appdir="/Applications" google-chrome
brew cask install --appdir="/Applications" vagrant
brew cask install --appdir="/Applications" spotify
brew cask install --appdir="/Applications" karabiner
brew cask install --appdir="/Applications" shiftit
brew cask install --appdir="/Applications" transmission

###############################################################################
# ZEN PYTHON ENVIROMENT MANAGER                                               #
###############################################################################

git clone "https://github.com/zhiyanfoo/zen" ~/tools/zen
./~/tools/zen/installation.sh

zen create zhiyan
zen use zhiyan
pip3 install neovim
pip3 install ipython
pip3 install bpython


###############################################################################
# Manual                                                                      #
###############################################################################

# preferences for iterm need to be changed manually, profile -> colors and
# profile -> general -> command -> /usr/local/bin/zsh

# Haskell, takes a long time
# curl -sSL https://get.haskellstack.org/ | sh
